### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by sharkwouter** [han-kwang/covid19#3]
I accidentally ran into this project and it looks quite interesting, but I don't know how to get it running. I tried fixing some issues I was running into, but I haven't been able to fix it so far. Are there any instructions?

**Comment by han-kwang** [comment]
There was a missing file, needed by nlcovidstats.py. The file is now included in the repository. You should be able to run that script from Spyder now.

The script process_casus_data.py should run out-of-the-box, but if you don't want to wait for it to download 5 GB of uncompressed csv files, it's better to check the doc of the function casus_analysis.download_rivm_casus_files().

**Comment by sharkwouter** [comment]
Thanks for pushing the file which was needed for the execution. I'm now able to run ``nlcovidstats.py``. I also got your email and yes, it's not a problem that it is in Dutch. I'm not a pro with Spyder and Jupyter unfortunately, but I'll try if I can get it to work some other time.

You don't have to maintain backwards compatibility for me. I'm just playing around a bit

**Comment by han-kwang** [comment]
I pushed an update that, in addition to your fixes, should make the scripts more suitable for command-line use. The main reason for working interactively with Spyder is that it takes some time to load the data. Then you can interactively do operations on the loaded data without the startup overhead. And if the script crashes, you can enter the debugger. It is as if you type `python -i -m sccript_name.py` .

**Comment by sharkwouter** [comment]
Thanks! That makes some sense. I'll see if I can make it work

**Comment by sharkwouter** [comment]
Ah cool, now I am able to get some nice graphs from ``nlcovidstats.py``.

**Comment by han-kwang** [comment]
OK, how about the process_casus_data.py script? I copy my response from https://github.com/han-kwang/covid19/pull/4 :

I noticed two things [in your error messages]:

* Only two csv files were loaded although it announced that it was going to load 145 of them. Something is wrong there, or maybe you hardcoded to only get the first two. If you do that, the data processing won't work. It needs at least a month of data, preferably starting from at least October.  Anyway, to get the full dataset, download the ZIP from https://github.com/mzelst/covid-19/archive/master.zip ; unzip the CSV files in data-rivm/casus-datasets/ into the folder data-casus/ and compress all of them using gzip.

* The error message seems to be related to pickling/unpickling (this is done for caching purposes) in some versions of Pandas. [(Stackoverflow)](https://stackoverflow.com/questions/63559007/unpickling-dictionary-that-holds-pandas-dataframes-throws-attributeerror-dataf) If you downgraded/upgraded pandas, try deleting the cache file (in the cache/ folder). Or wait for the cache to expire (1 hour).

**Comment by han-kwang** [comment]
I'm closing this because of updates in code and README.
